version: '3.2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        image: php:7-fpm
        volumes:
            - .:/var/www/html
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: gandalf
            MYSQL_PASSWORD: notpass
            MYSQL_DATABASE: magic